fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: requirements.txt
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        args: [
          --strict-optional,
          --no-implicit-optional,
          --warn-unused-ignores,
          --check-untyped-defs,
          --warn-unreachable,
          --strict-equality
        ]
        additional_dependencies: [
          'python-dotenv',
          'django',
          'djangorestframework',
          'django-stubs',
          'djangorestframework-stubs',
          'django-cors-headers'
        ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        files: ^frontend\/[^\/]+
