name: frontend

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
    prettier:
      name: Run PR Frontend Formatting Check
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node
          uses: actions/setup-node@v3

        - name: Install prettier
          run: npm install prettier

        - name: Run prettier
          working-directory: ./frontend
          run: |
            npx prettier . --check
